files:
  ignore:
  - 'scss/assets/**/*.scss'
  - 'scss/vars/_include-fonts.scss'
rules:
  brace-style:
  - 2
  - allow-single-line: true
  border-zero:
  - 2
  - convention: zero
  empty-line-between-blocks:
  - 2
  final-newline: 0
  indentation: 0
  property-sort-order: 0
  single-line-per-selector: 2
  extends-before-declarations: 2
  mixins-before-declarations: 2
  mixin-name-format:
  - 2
  - allow-leading-underscore: false
    convention: hyphenatedlowercase
  shorthand-values: 2
  hex-notation:
  - 2
  - style: lowercase
  clean-import-paths:
  - 2
  - filename-extension: false
    leading-underscore: false
  class-name-format:
  - 2
  - allow-leading-underscore: false
    convention: hyphenatedbem
    convention-explanation: 'classname__classname__classname'
  space-after-comma: 2
  space-after-colon: 2
  space-before-brace:
  - 2
  - include: true
  one-declaration-per-line: 2
  leading-zero: 2
  hex-length:
  - 2
  - style: short
  nesting-depth:
  - 2
  - max-depth: 4
  quotes:
  - 2
  - style: single
  no-color-literals: 2
  no-color-keywords: 2
  no-css-comments: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-trailing-whitespace: 2
  no-vendor-prefixes: 0
  no-important: 1
  url-quotes: 2
  variable-name-format:
  - 0
  - allow-leading-underscore: false
    convention: hyphenatedlowercase
  variable-for-property:
  - 2
  - properties: []
  zero-unit: 2
  placeholder-in-extend: 0
  no-url-domains: 0
  no-url-protocols: 0
  pseudo-element: 0
